# Generated by Django 5.1.2 on 2024-11-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesapp', '0003_alter_recipe_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='food_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='time_taken',
            field=models.IntegerField(null=True),
        ),
    ]
