# Generated by Django 5.1.2 on 2024-11-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesapp', '0004_recipe_food_type_recipe_time_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='style',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
